import { writeFileSync } from "fs";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";
import { readExportHtmlTemplateScript } from "../src/core/export-html/template-script.ts";

const scriptPath = fileURLToPath(import.meta.url);
const packageDir = resolve(dirname(scriptPath), "..");
const templateDir = resolve(packageDir, "src/core/export-html");
const templatePath = resolve(templateDir, "template.js");
const generatedHeader = [
	"// @generated by packages/coding-agent/scripts/generate-export-html-template.ts; DO NOT EDIT.",
	"// Source chunks live in template-js/ and are composed at export time by template-script.ts.",
	"",
].join("\n");

writeFileSync(templatePath, generatedHeader + readExportHtmlTemplateScript(templateDir), "utf-8");
