import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, test } from "vitest";
import { bunExecutable, spawnSyncCollect } from "../helpers/runtime.js";

interface VersionedPackageJson {
	name: string;
	version: string;
	private?: boolean;
	dependencies?: Record<string, string>;
	optionalDependencies?: Record<string, string>;
}

interface NpmLockEntry {
	name?: string;
	version?: string;
	link?: boolean;
	resolved?: string;
	dependencies?: Record<string, string>;
	optionalDependencies?: Record<string, string>;
}

interface NpmLock {
	name: string;
	lockfileVersion: number;
	requires: boolean;
	packages: Record<string, NpmLockEntry>;
}

interface BumpResult {
	exitCode: number | null;
	stdout: string;
	stderr: string;
}

function writeJson(path: string, value: VersionedPackageJson | NpmLock): void {
	writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function readJson(path: string): VersionedPackageJson {
	return JSON.parse(readFileSync(path, "utf8")) as VersionedPackageJson;
}

function readLock(path: string): NpmLock {
	return JSON.parse(readFileSync(path, "utf8")) as NpmLock;
}

function createFixtureRoot(): string {
	const root = mkdtempSync(join(tmpdir(), "atomic-bump-version-"));
	mkdirSync(join(root, "packages", "alpha"), { recursive: true });
	mkdirSync(join(root, "packages", "beta"), { recursive: true });
	mkdirSync(join(root, "packages", "natives", "native"), { recursive: true });
	mkdirSync(join(root, "crates", "native"), { recursive: true });

	writeJson(join(root, "package.json"), {
		name: "fixture-monorepo",
		version: "0.1.0",
		private: true,
		dependencies: {
			"@bastani/atomic-natives": "0.1.0",
		},
	});
	writeFileSync(
		join(root, "Cargo.toml"),
		'[workspace]\nmembers = ["crates/native"]\n\n[workspace.package]\nversion = "0.1.0"\nedition = "2024"\n',
	);
	writeFileSync(
		join(root, "Cargo.lock"),
		'# This file is automatically @generated by Cargo.\n\n[[package]]\nname = "atomic-native"\nversion = "0.1.0"\n\n[[package]]\nname = "atomic-waker"\nversion = "1.1.2"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = "fixture-checksum"\n\n[[package]]\nname = "third-party"\nversion = "9.9.9"\n',
	);
	writeJson(join(root, "packages", "alpha", "package.json"), {
		name: "@fixture/alpha",
		version: "0.1.0",
		private: true,
		optionalDependencies: { "@bastani/atomic-natives-linux-x64-musl": "0.1.0" },
	});
	writeJson(join(root, "packages", "beta", "package.json"), {
		name: "@fixture/beta",
		version: "0.1.0",
		private: true,
	});
	writeFileSync(
		join(root, "packages", "alpha", "README.md"),
		'<img src="https://img.shields.io/badge/version-0.1.0-blue" alt="Version 0.1.0">\n',
	);
	writeFileSync(
		join(root, "crates", "native", "Cargo.toml"),
		'[package]\nname = "atomic-native"\nversion = "0.1.0"\nedition = "2024"\n',
	);
	writeFileSync(
		join(root, "packages", "natives", "native", "index.js"),
		`/* auto-generated by NAPI-RS */
if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK) {
  throw new Error(\`Native binding package version mismatch, expected 0.1.0 but got \${bindingPackageVersion}\`)
}
if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK) {
  throw new Error(\`Native binding package version mismatch, expected 0.1.0 but got \${bindingPackageVersion}\`)
}
`,
	);
	// The lockfile is not optional decoration in this fixture.
	//
	// `npm ci` refuses to install when package-lock.json and a package.json
	// disagree -- unlike `bun install --frozen-lockfile`, which tolerated exactly
	// that and is why the lock used to be left at its placeholder. publish.yml
	// installs from the tagged release commit, so a lock the stamp misses breaks
	// the release rather than a test. Without this file `npmLockTargets()`
	// returns [] and `bumpNpmLock` is never entered by any test.
	writeJson(join(root, "package-lock.json"), {
		name: "fixture-monorepo",
		lockfileVersion: 3,
		requires: true,
		packages: {
			"": {
				name: "fixture-monorepo",
				version: "0.1.0",
				dependencies: { "@bastani/atomic-natives": "0.1.0" },
			},
			"node_modules/@bastani/atomic-natives": { resolved: "packages/natives", link: true },
			"node_modules/@fixture/alpha": { resolved: "packages/alpha", link: true },
			"node_modules/third-party": {
				version: "9.9.9",
				resolved: "https://registry.npmjs.org/third-party/-/third-party-9.9.9.tgz",
			},
			"packages/alpha": {
				name: "@fixture/alpha",
				version: "0.1.0",
				dependencies: { "@bastani/atomic-natives": "0.1.0", "third-party": "9.9.9" },
				optionalDependencies: {
					"@bastani/atomic-natives-linux-x64-gnu": "0.1.0",
					"@bastani/atomic-natives-linux-x64-musl": "0.1.0",
				},
			},
			"packages/beta": { name: "@fixture/beta", version: "0.1.0" },
			"packages/natives": { name: "@bastani/atomic-natives", version: "0.1.0" },
			// A nested third-party install under a workspace path -- the production
			// shape (@napi-rs/cli under packages/natives/node_modules) that a bare
			// `packages/` prefix check mistakes for a workspace entry.
			"packages/natives/node_modules/nested-tool": {
				version: "3.8.1",
				resolved: "https://registry.npmjs.org/nested-tool/-/nested-tool-3.8.1.tgz",
				dependencies: { "third-party": "9.9.9" },
			},
		},
	});

	return root;
}

function runBump(root: string, version: string): BumpResult {
	const result = spawnSyncCollect({
		cmd: [bunExecutable(), "run", join(process.cwd(), "scripts", "bump-version.ts"), version, "--root", root],
		stdout: "pipe",
		stderr: "pipe",
	});

	return {
		exitCode: result.exitCode,
		stdout: result.stdout.toString(),
		stderr: result.stderr.toString(),
	};
}

describe("scripts/bump-version.ts", () => {
	test("updates every versioned package manifest and README badge", () => {
		const root = createFixtureRoot();
		try {
			const result = runBump(root, "1.2.3-alpha.1");
			assert.equal(result.exitCode, 0, result.stderr);

			const rootPackageJson = readJson(join(root, "package.json"));
			assert.equal(rootPackageJson.version, "1.2.3-alpha.1");
			assert.equal(rootPackageJson.dependencies?.["@bastani/atomic-natives"], "1.2.3-alpha.1");
			const alphaPackageJson = readJson(join(root, "packages", "alpha", "package.json"));
			assert.equal(alphaPackageJson.version, "1.2.3-alpha.1");
			assert.equal(
				alphaPackageJson.optionalDependencies?.["@bastani/atomic-natives-linux-x64-musl"],
				"1.2.3-alpha.1",
			);
			assert.equal(readJson(join(root, "packages", "beta", "package.json")).version, "1.2.3-alpha.1");
			assert.match(readFileSync(join(root, "Cargo.toml"), "utf8"), /version = "1\.2\.3-alpha\.1"/);
			assert.match(
				readFileSync(join(root, "crates", "native", "Cargo.toml"), "utf8"),
				/version = "1\.2\.3-alpha\.1"/,
			);
			const cargoLock = readFileSync(join(root, "Cargo.lock"), "utf8");
			assert.match(cargoLock, /name = "atomic-native"\nversion = "1\.2\.3-alpha\.1"/);
			assert.match(cargoLock, /name = "atomic-waker"\nversion = "1\.1\.2"/);
			assert.match(cargoLock, /name = "third-party"\nversion = "9\.9\.9"/);
			assert.match(
				readFileSync(join(root, "packages", "alpha", "README.md"), "utf8"),
				/version-1\.2\.3--alpha\.1-blue" alt="Version 1\.2\.3-alpha\.1"/,
			);
			const nativeIndex = readFileSync(join(root, "packages", "natives", "native", "index.js"), "utf8");
			assert.match(nativeIndex, /bindingPackageVersion !== '1\.2\.3-alpha\.1'/);
			assert.match(nativeIndex, /expected 1\.2\.3-alpha\.1 but got \$\{bindingPackageVersion\}/);
			assert.doesNotMatch(nativeIndex, /0\.1\.0/);

			// The npm lockfile is stamped in place, or `npm ci` on the tagged release
			// commit refuses the tree the stamp just produced.
			const lock = readLock(join(root, "package-lock.json"));
			assert.equal(lock.packages["packages/alpha"]?.version, "1.2.3-alpha.1");
			assert.equal(lock.packages["packages/beta"]?.version, "1.2.3-alpha.1");
			assert.equal(lock.packages["packages/natives"]?.version, "1.2.3-alpha.1");
			// First-party ranges inside a workspace entry move with it, in every
			// section, including the platform-suffixed native packages.
			assert.equal(
				lock.packages["packages/alpha"]?.optionalDependencies?.["@bastani/atomic-natives-linux-x64-musl"],
				"1.2.3-alpha.1",
			);
			assert.equal(lock.packages["packages/alpha"]?.dependencies?.["@bastani/atomic-natives"], "1.2.3-alpha.1");
			assert.equal(
				lock.packages["packages/alpha"]?.optionalDependencies?.["@bastani/atomic-natives-linux-x64-gnu"],
				"1.2.3-alpha.1",
			);
			// Third-party pins and the resolved link entries are left exactly alone:
			// rewriting either would invalidate the lock rather than stamp it.
			assert.equal(lock.packages["packages/alpha"]?.dependencies?.["third-party"], "9.9.9");
			assert.equal(lock.packages["node_modules/third-party"]?.version, "9.9.9");
			// A nested node_modules entry under a workspace path is third-party,
			// not a workspace entry: stamping it desynchronizes the lock and makes
			// `npm ci` refuse the tagged release commit.
			assert.equal(lock.packages["packages/natives/node_modules/nested-tool"]?.version, "3.8.1");
			assert.equal(
				lock.packages["packages/natives/node_modules/nested-tool"]?.dependencies?.["third-party"],
				"9.9.9",
			);
			assert.equal(lock.packages["node_modules/@fixture/alpha"]?.link, true);
			assert.equal(lock.packages["node_modules/@fixture/alpha"]?.version, undefined);
			assert.match(result.stdout, /package-lock\.json: 3 workspace entries → 1\.2\.3-alpha\.1/u);
		} finally {
			rmSync(root, { recursive: true, force: true });
		}
	});

	test("rejects v-prefixed, legacy-numeric, and malformed alpha prerelease versions", () => {
		// The prerelease convention is `-alpha.N` with the revision starting at 1.
		// Legacy numeric prereleases (the old `-0`/`-4` style suffix) and any other
		// suffix shape are rejected.
		const invalidVersions = [
			"v1.2.3",
			"1.2.3-0",
			"1.2.3-alpha.0",
			"1.2.3-alpha",
			"1.2.3-alpha.01",
			"1.2.3-rc.1",
			"01.2.3",
		];

		for (const version of invalidVersions) {
			const root = createFixtureRoot();
			try {
				const result = runBump(root, version);
				assert.notEqual(result.exitCode, 0, `${version} should be rejected`);
				assert.match(result.stderr, /Expected MAJOR\.MINOR\.PATCH or MAJOR\.MINOR\.PATCH-alpha\.REVISION/);
				assert.equal(readJson(join(root, "package.json")).version, "0.1.0");
				assert.equal(readJson(join(root, "packages", "alpha", "package.json")).version, "0.1.0");
				assert.equal(readLock(join(root, "package-lock.json")).packages["packages/alpha"]?.version, "0.1.0");
			} finally {
				rmSync(root, { recursive: true, force: true });
			}
		}
	});

	/**
	 * A repository with no npm lockfile is still stampable.
	 *
	 * `npmLockTargets()` is conditional on the file existing, and this is the
	 * shape every other test used to run in -- which is exactly why the stamping
	 * branch went untested. Keeping one explicit case here means the absence is a
	 * decision rather than the default.
	 */
	test("a root without an npm lockfile is stamped without one", () => {
		const root = createFixtureRoot();
		try {
			rmSync(join(root, "package-lock.json"));
			const result = runBump(root, "1.2.3");
			assert.equal(result.exitCode, 0, result.stderr);
			assert.equal(readJson(join(root, "package.json")).version, "1.2.3");
			assert.doesNotMatch(result.stdout, /package-lock\.json/u);
		} finally {
			rmSync(root, { recursive: true, force: true });
		}
	});
});
